base_url = "https://xjump.me"
compile_sass = true
title = "@xjump"
description = "notes by xjump"
highlight_code = true
paginate_by = 5
generate_rss = true
taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
author = "@xjump"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
#    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/tags/all", name = "Archive"},
    {url = "$BASE_URL/rss.xml", name = "RSS"},
    {url = "$BASE_URL/about", name = "About"},
]
even_title = "@xjump"

katex_enable = true
katex_auto_render = true

